openapi: 3.0.2
info:
    title: magdalena
    version: 1.0.0
    description: magdalena OpenAPI 2.0 specification.
    contact:
        name: Raniere Gaia Costa da Silva
        email: Raniere.CostadaSilva@gesis.org
    license:
        name: GNU AGPLv3
        url: 'https://www.gnu.org/licenses/agpl.txt'
paths:
    /:
        post:
            requestBody:
                description: Git repository details.
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/build-request'
                required: true
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/task'
                    description: Task to build page was created.
            security:
                -
                    gesis: []
            summary: Convert Git repository into desired format.
            description: Convert Git repository into HTML.
    '/result/{id}':
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/result-response'
                '404': {}
            summary: Get result of request.
            description: Get JSON information of the result.
        parameters:
            -
                name: id
                description: ID of the task.
                schema:
                    type: string
                in: path
                required: true
    '/sse/result/{id}/':
        get:
            responses:
                '200': {}
                '404': {}
            summary: Get result of request as server-sent event.
            description: Server-sent event with result of task.
        parameters:
            -
                name: id
                description: ID of the task.
                schema:
                    type: string
                in: path
                required: true
    '/download/{id}':
        get:
            responses:
                '200': {}
                '404': {}
            summary: Download resource created.
            description: 'Download ZIP, HTML or plain text file depending of the request.'
        parameters:
            -
                name: id
                description: ID of the task.
                schema:
                    type: string
                in: path
                required: true
components:
    schemas:
        build-request:
            title: Root Type for build-request
            description: ''
            required:
                - target_format
                - response
                - source_url
            type: object
            properties:
                source_url:
                    description: Git repository URL.
                    type: string
                filename:
                    description: Filename of the file to convert. Default to README.md.
                    type: string
                git_commit_id:
                    description: Git commit ID.
                    type: string
                target_format:
                    type: array
                    items:
                        type: string
                response:
                    enum:
                        - download
                        - forward
                    type: string
            example:
                source_url: 'https://github.com/GESIS-Methods-Hub/minimal-example-qmd-rstats-units'
                filename: index.qmd
                git_commit_id: 996dbe13501f6cf3f2811843bee68cc5295dd0ff
                target_format:
                    - html
                response: download
        task:
            title: Root Type for task
            description: ''
            type: object
            properties:
                id:
                    type: string
            example:
                id: '123'
        result-response:
            title: Root Type for result-response
            description: Result of a request.
            type: object
            properties:
                ready:
                    type: boolean
                successful:
                    type: boolean
                value:
                    type: string
            example:
                ready: true
                successful: true
                value: Hello world
    securitySchemes:
        gesis:
            flows:
                implicit:
                    authorizationUrl: 'https://login.gesis.org/'
            type: oauth2
            description: GESIS Keycloak Single-Sing On
