# SPDX-FileCopyrightText: 2023 - 2024 GESIS - Leibniz-Institut für Sozialwissenschaften
# SPDX-FileContributor: Raniere Gaia Costa da Silva <Raniere.CostadaSilva@gesis.org>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

swagger: '2.0'
info:
    title: New API
    version: 1.0.0
    description: magdalena OpenAPI 2.0 specification.
    contact:
        name: Raniere Gaia Costa da Silva
        email: Raniere.CostadaSilva@gesis.org
    license:
        name: GNU AGPLv3
        url: 'https://www.gnu.org/licenses/agpl.txt'
consumes:
    - application/json
produces:
    - application/json
paths:
    /:
        post:
            parameters:
                -
                    name: body
                    description: Git repository details.
                    in: body
            responses:
                '201': {}
            description: Convert Git repository into HTML.
    '/result/{id}':
        get:
            responses:
                '200': {}
                '404': {}
        parameters:
            -
                name: id
                description: ID of the task.
                in: path
                required: true
                type: string
    '/sse/result/{id}/':
        get:
            responses:
                '200': {}
                '404': {}
            summary: Server-sent event with result of task
        parameters:
            -
                name: id
                description: ID of the task.
                in: path
                required: true
                type: string
    '/download/{id}':
        get:
            responses:
                '200': {}
                '404': {}
        parameters:
            -
                name: id
                description: ID of the task.
                in: path
                required: true
                type: string
definitions:
    build-request:
        title: Root Type for build-request
        description: ''
        required:
            - target_format
            - response
            - source_url
        type: object
        properties:
            source_url:
                description: Git repository URL.
                type: string
            filename:
                type: string
            git_commit_id:
                description: Git commit ID.
                type: string
            target_format:
                type: array
                items:
                    type: string
            response:
                enum:
                    - download
                    - forward
                type: string
        example:
            source_url: 'https://github.com/GESIS-Methods-Hub/minimal-example-qmd-rstats-units'
            filename: index.qmd
            git_commit_id: 996dbe13501f6cf3f2811843bee68cc5295dd0ff
            target_format:
                - html
            response: download
