services:
  magdalena:
    build:
      context: .
      target: dev
    volumes:
      - type: bind
        source: app.py
        target: /var/magdalena/app.py
      - type: bind
        source: methodshub.py
        target: /var/magdalena/methodshub.py
      - type: bind
        source: templates
        target: /var/magdalena/templates
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    expose:
      - "5000"
    ports:
      - "5000:5000"
    command: flask run --host 0.0.0.0 --port 5000 --reload --debug --debugger
