# SPDX-FileCopyrightText: 2023 - 2024 GESIS - Leibniz-Institut für Sozialwissenschaften
# SPDX-FileContributor: Raniere Gaia Costa da Silva <Raniere.CostadaSilva@gesis.org>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

services:

  sphinx:
    profiles:
      - docs
    image: docker-private-releases.gesis.intra/gesis/methods-hub/sphinx/sphinx:7.2.6-make
    command: sphinx-autobuild --host 0.0.0.0 source build
    volumes:
      - type: bind
        source: docs/source
        target: /docs/source
    expose:
      - "8000"
    ports:
      - "8000:8000"

  swagger-editor:
    profiles:
      - docs
    image: swaggerapi/swagger-editor:v4.12.1
    environment:
      SWAGGER_FILE: /var/magdalena/openapi/magdalena.yaml
    volumes:
      - type: bind
        source: docs/source/_static/openapi
        target: /var/magdalena/openapi
    expose:
      - "8800"
    ports:
      - "8800:8080"

  reverse-proxy:
    depends_on:
      - keycloak
      - magdalena
    image: nginx:1.25.4-alpine-slim
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx/sites-enabled
        target: /etc/nginx/conf.d

  # On 20 March 2024, Redis moved away from the BSD license.
  # The last Redis release under the BSD license was version 7.2.4.
  #
  # In the future, we might want to move to https://valkey.io/
  redis:
    image: redis:7.2.4-alpine3.19

  rabbitmq:
    image: rabbitmq:3.13-alpine
    environment:
      RABBITMQ_DEFAULT_USER: celery
      RABBITMQ_DEFAULT_PASS: 123

  worker:
    depends_on:
      - redis
      - rabbitmq
    build:
      context: .
      target: dev
    volumes:
      - type: bind
        source: .
        target: /var/magdalena
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        # This must be the same as MAGDALENA_SHARED_DIR
        # because of Docker outside of Docker
        source: /tmp/magdalena-shared-volume
        target: /tmp/magdalena-shared-volume
    environment:
      RABBITMQ_DEFAULT_USER: celery
      RABBITMQ_DEFAULT_PASS: 123
    command: celery -A worker worker --loglevel=INFO

  magdalena:
    depends_on:
      keycloak:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      worker:
        condition: service_started
    build:
      context: .
      target: dev
    environment:
      # Flask
      LOG_LEVEL: debug

      # JWT
      JWT_ISSUER: http://keycloak.gesis.dev/realms/gesis

      # Keycloak
      KEYCLOAK_SCHEME: http
      KEYCLOAK_DOMAIN: keycloak.gesis.dev
      KEYCLOAK_REALM: gesis
      KEYCLOAK_CLIENT: gesis-methodshub-ember-client

      # Keycloak (Backend)
      # 
      # Used to retrieve the public key from Keycloak.
      BACKEND_KEYCLOAK_SCHEME: http
      BACKEND_KEYCLOAK_DOMAIN: keycloak:8080

      # Keycloak (Frontend)
      # 
      # Used to configure keycloak-js.
      # FRONTEND_KEYCLOAK_SCHEME: http
      # FRONTEND_KEYCLOAK_DOMAIN: keycloak.gesis.dev

      # magdalena
      MYBINDER_URL: https://notebooks.gesis.org/binder
      MAGDALENA_SHARED_DIR: /tmp/magdalena-shared-volume
      MAGDALENA_GRAPHQL_TARGET_URL: http://localhost/graphql
      MAGDALENA_GRAPHQL_TARGET_TOKEN: 123456
    volumes:
      - type: bind
        source: .
        target: /var/magdalena
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        # This must be the same as MAGDALENA_SHARED_DIR
        # because of Docker outside of Docker
        source: /tmp/magdalena-shared-volume
        target: /tmp/magdalena-shared-volume
    expose:
      - "5000"
    ports:
      - "4200:5000"
    command: flask run --host 0.0.0.0 --port 5000 --reload --debug --debugger

  keycloak:
    extends:
      file: keycloak/compose.yaml
      service: keycloak
    depends_on:
      - keycloak-db

  keycloak-db:
    extends:
      file: keycloak/compose.yaml
      service: keycloak-db

volumes:
  keycloak-data:
