services:
  magdalena:
    build:
      context: .
      target: dev
    volumes:
      - type: bind
        source: .
        target: /var/magdalena
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /tmp/magdalena-shared-volume
        target: /tmp/magdalena-shared-volume
    expose:
      - "5000"
    ports:
      - "5000:5000"
    command: flask run --host 0.0.0.0 --port 5000 --reload --debug --debugger
