# SPDX-FileCopyrightText: 2023 - 2024 GESIS - Leibniz-Institut für Sozialwissenschaften
# SPDX-FileContributor: Raniere Gaia Costa da Silva <Raniere.CostadaSilva@gesis.org>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

services:

  sphinx:
    image: docker-private-releases.gesis.intra/gesis/methods-hub/sphinx/sphinx:7.2.6-make
    command: sphinx-autobuild --host 0.0.0.0 source build
    volumes:
      - type: bind
        source: docs/source
        target: /docs/source
    expose:
      - "8000"
    ports:
      - "8000:8000"

  swagger-editor:
    image: swaggerapi/swagger-editor:v4.12.1
    environment:
      SWAGGER_FILE: /var/magdalena/openapi/magdalena.yaml
    volumes:
      - type: bind
        source: docs/source/_static/openapi
        target: /var/magdalena/openapi
    expose:
      - "8800"
    ports:
      - "8800:8080"

  reverse-proxy:
    depends_on:
      - keycloak
      - magdalena
    image: nginx:1.25.4-alpine-slim
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx/sites-enabled
        target: /etc/nginx/conf.d

  magdalena:
    depends_on:
      keycloak:
        condition: service_healthy
        restart: true
    build:
      context: .
      target: dev
    environment:
      # Flask
      LOG_LEVEL: debug

      # JWT
      JWT_ISSUER: http://localhost:8080/realms/Gesis

      # Keycloak
      KEYCLOAK_SCHEME: http
      KEYCLOAK_DOMAIN: keycloak.gesis.dev
      KEYCLOAK_REALM: gesis
      KEYCLOAK_CLIENT: gesis-methodshub-ember-client

      # Keycloak (Backend)
      BACKEND_KEYCLOAK_SCHEME: http
      BACKEND_KEYCLOAK_DOMAIN: keycloak:8080

      # Keycloak (Frontend)
      FRONTEND_KEYCLOAK_SCHEME: http
      FRONTEND_KEYCLOAK_DOMAIN: keycloak.gesis.dev

      # magdalena
      MYBINDER_URL: https://notebooks.gesis.org/binder
      MAGDALENA_SHARED_DIR: /tmp/magdalena-shared-volume
      MAGDALENA_GRAPHQL_TARGET_URL: http://localhost/graphql
      MAGDALENA_GRAPHQL_TARGET_TOKEN: 123456
    volumes:
      - type: bind
        source: .
        target: /var/magdalena
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        # This must be the same as MAGDALENA_SHARED_DIR
        # because of Docker outside of Docker
        source: /tmp/magdalena-shared-volume
        target: /tmp/magdalena-shared-volume
    expose:
      - "5000"
    ports:
      - "4200:5000"
    command: flask run --host 0.0.0.0 --port 5000 --reload --debug --debugger

  keycloak:
    extends:
      file: keycloak/compose.yaml
      service: keycloak
    depends_on:
      - keycloak-db

  keycloak-db:
    extends:
      file: keycloak/compose.yaml
      service: keycloak-db

volumes:
  keycloak-data:
